tap "tksohishi/tap"
brew "agent-browser"
brew "awscli"
brew "bats-core"
brew "caddy"
brew "cocoapods"
brew "coreutils"
brew "ctx7"
brew "direnv"
brew "dnsmasq"
brew "fd"
brew "ffmpeg"
brew "foundry"
brew "gh"
brew "gitleaks"
brew "go"
brew "hermes-agent"
brew "httpie"
brew "gogcli"
brew "imagemagick"
brew "jq"
brew "just"
brew "kubo"
brew "libusb"
brew "libimobiledevice" # Tauri iOS builds (Lifelane)
brew "mas"
brew "miller"
brew "mise"
brew "mosh"
brew "opencode"
brew "pandoc"
brew "pdfgrep"
brew "poppler"
brew "rclone"
brew "render"
brew "ripgrep"
brew "rustup"
brew "scribe"
brew "seats"
brew "sheets"
brew "starship"
brew "summarize"
brew "tailspin"
brew "tgcli"
brew "tig"
brew "tmux"
brew "tree"
brew "uv"
brew "wayfinder"
brew "xcodegen"
brew "zoxide"
cask "1password"
cask "1password-cli"
cask "alfred"
cask "brave-browser"
cask "claude"
cask "codex"
cask "discord"
cask "dropbox"
cask "firefox"
cask "font-d2coding"
cask "font-inter"
cask "font-jetbrains-mono-nerd-font"
cask "font-roboto"
cask "font-sf-mono-nerd-font-ligaturized"
cask "font-sf-pro"
cask "ghostty"
cask "google-chrome"
cask "google-chrome@canary"
cask "gcloud-cli"
cask "google-japanese-ime" # Password prompt: input method
cask "granola"
cask "ledger-wallet"
cask "libreoffice"
cask "logi-options+"
cask "notion-calendar"
cask "notion-cli"
cask "openusage"
cask "simple-comic"
cask "slack"
cask "spotify"
cask "ticktick"
cask "visual-studio-code" # Password prompt: shell command
cask "zed"
cask "zoom" # Password prompt: audio device

mas "Amphetamine", id: 937984704
mas "CotEditor", id: 1024640650
mas "Keynote", id: 409183694
mas "NordVPN", id: 905953485
mas "Pages", id: 409201541
mas "Speedtest", id: 1153157709
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
# Manual install: Claude Code (claude install)
# Manual install: CuaDriver (bundled with Claude desktop)
cask "chatgpt"
# Manual install: Eika (self-built)
# Manual install: Kanary (scripts/install-kanary.sh)
mas "Xcode", id: 497799835
