[settings]
trusted_config_paths = ["~/.dotfiles"]

[tools]
node = { version = "24.13", postinstall = "corepack enable pnpm" }
python = "3.13"
"aqua:openai/codex" = "latest"
bun = "latest"
deno = "latest"
